### 지난시간 복습

In [ ]:
# numpy를 시작했음.
# 뼈대를 잡았음.
# numpy 는 라이브러리인데 그 안에 있는 array 라는 데이터 구조. 더 정확히는 ndarray 가 우리가 사용할 데이터의 가장 기본이 되는 애
# ndarray는 프로그래밍 적으로는 array 인데, vertorize(element-wised) 하게 연산자 오버로딩함.
# C 로 만들었고 하드웨어 까지 최대한 활용할 수 있기 때문에 파이썬으로 데이터 관련해서 얘를 안쓰는 경우가 없음.
# array 는 거의 모든 수학적 컨셉을 대신할 수 있다.
# 또한 강력하고 쉽다.
# 어제 그 관점에서 만드는 경우는 별로 없어서 대충했음. 데이터 관련해서 첫번째 알아야 하는 것은 데이터를 선택하고 추출하는 것.
# 그것을 우리는 인덱싱과 슬라이싱이라고 했음.
# 기본적으로 5가지의 인덱싱과 슬라이싱을 배웠음. 그런데 어제 마지막 [...]을 안배웠음.

In [ ]:
# 인덱싱과 슬라이싱은 array 구조가 시퀀스 라서 당연히 됨.
# 이것도 넘파이에서 확장을 시켜서 5가지 기능이 더 있는 것. 그것도 (연산자)오버로딩 혹은 (시퀀스 클래스 확장)오버라이딩이라고 할 수 있음
# 시퀀스 클래스 확장이라고 하면, 덕타이핑 / abstraction(추상화) / 만들어진 애로 상속받는 방법
# 그런데 넘파이는 C로 만들어짐.
# 그 넘파이 고유의 특징들을 몇가지 봄.
# property 중에서 shape, dtype, size... 연산. 브로드캐스트, ufuction 까지 봤음.

In [ ]:
# MATLAB 이랑 비슷한 기능을 가짐. 많이 가져왔기 때문에. 여기서 가져온 또 하나가 matplotlib. 그 문법을 그대로 가져옴
# nd 는 n차원 dimension
# 데이터가 많으면 한눈에 보기 힘드니까 shape

### 수업

In [2]:
import tensorflow as tf

In [5]:
a = tf.keras.datasets.mnist.load_data()
# 너무 많은 ... 으로 대치를 함.

In [6]:
# len 테크닉
a

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [7]:
len(a)

2

In [8]:
x, y = a

In [9]:
x

(array([[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        ...,
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],

In [10]:
len(x)

2

In [11]:
(X_train, y_train),(X_test, y_test) = a
# 홀드 아웃
# 트레이닝할 때 X는 관례로 대문자. 매트릭스라서
# y는 벡터로 나와서 소문자(관례상).

In [12]:
X_train  # 앨립스
# 데이터 타입 unit8 => 이미지 데이터 셋
# 이런 데이터 타입은 C 언어로 만들었기 때문 => u 가 붙으면 unsigned. 부호가 없음

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [13]:
...  # 파이썬 공식 연산자

Ellipsis

In [ ]:
# ... 가 있을 때 아래 두 개는 꼭 해봐야 함.

In [14]:
X_train.shape # shape 을 치면 텐서의 모양도 알 수 있고, 차원도 알 수 있다.

(60000, 28, 28)

In [16]:
X_train.ndim # 이것은 shape 로 알 수 있음.

3

In [17]:
# 원소의 개수
X_train.size

47040000

In [18]:
X_train.itemsize

1

In [15]:
X_train.dtype  # stride 라는 개념에서 나올 것.
# 8 비트는 1바이트.

dtype('uint8')

In [ ]:
# shape이 중요한 이유는 수학적으로 매트릭스 연산을 하기 위해서. 이를 알면 ndim, size 알 필요 없음.
# tensor에 __repr__ 하면 shape, dtype 이 나옴

In [19]:
X_train.data  # 실질적 데이터 구조는 일렬로 쭉 이어져 있음

In [ ]:
# 실제 데이터 타입은 ndarray.

In [20]:
# Creation.
# 우리가 넘파이 데이터를 만드는 경우는 거의 없을 것.
import numpy as np
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [21]:
np.array(1,2,3,4) # object 는 한 개 따라서 오류나는 것
# array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [22]:
# container
# 한 개로 묶는 것.
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b
# 그런데 tuple도 됨.
# 덕 타이핑 ; 묶는 기능만 있으면 다 받아주기 때문에.
# homo 라서 큰 데이터 형태로 맞춰 줌 => corecion(묵시적 형변환)

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [26]:
a = np.arange(25).reshape(5,5)
a[[0,0],[3,4]]

array([3, 4])

In [24]:
a[[0,0],[3,4]]

array([3, 4])

In [25]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [27]:
np.zeros((3,5))
# zeros(shape, dtype=float, order='C', *, like=None)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.zeros([3,5])
# 함수의 인자로 mutable 넘기는 거는 초보적 실수임.

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
# mutable 의 위험성
def x(a:list['T']):   # 어노테이션
    a.append('x')

In [30]:
x.__annotations__

{'a': list['T']}

In [31]:
def x(a):
    return a.append('x')

In [32]:
a = [3,4,5]
x(a)
# 리턴값 왜 없지?

In [33]:
# list의 리턴값 3가지 종류
# append 는 리턴값 없고 자기자신 변하는 것.
a
# 집어넣은 값 자체가 변해버림 => 문제점.
# 따라서 함수에 mutable 집어넣는 순간 싸대기 맞음

[3, 4, 5, 'x']

In [34]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [35]:
# 파이썬의 range와 똑같음 : 기본적으로 homo
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [36]:
import math

In [37]:
math.pi

3.141592653589793

In [38]:
np.pi

3.141592653589793

In [40]:
math.pi == np.pi, math.pi is np.pi

(True, False)

In [42]:
np.linspace(1, 50, 10)
# binning
# 어디서 어디까지 몇 등분할 때 쓸 것.

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [ ]:
# 컴퓨터 세상에서 연속되게 보이게 하기 위해서 아주 잘게 자름.
# 즉 넘파이에서 값 쉽게 그리는 게 아주 많음을 보여주는 것.
# 넘파이에서 잊으면 안되는 것이 lookfor

In [ ]:
# 모양을 바꾸는 테크닉이 중요함 -> 모양이 안맞으면 연산이 안되기 때문에.
# 기본적인 연산
# element-wise 연산 - 하드웨어 적으로 지원됨
# 모양 같아야 하는 점이 제일 중요함 cf. 브로드캐스트

In [ ]:
# 파이썬의 오픈 cv 는 넘파이로 만들어져 있음. 

In [43]:
a = np.array([[1,2,3]])
b = np.array([[1],[2],[3]])

In [47]:
a, a.shape

(array([[1, 2, 3]]), (1, 3))

In [48]:
b, b.shape

(array([[1],
        [2],
        [3]]),
 (3, 1))

In [46]:
a + b

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [50]:
np.ogrid[1:10, 1:10]

[array([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]),
 array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])]

In [51]:
len(np.ogrid[1:10, 1:10])

2

In [52]:
x, y = np.ogrid[1:10, 1:10]

In [53]:
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [54]:
y

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [55]:
# 이것들은 좌표축 만들 때 많이 씀
x + y

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [ ]:
# 기본 연산은 element-wise ; 모양이 같으면 원소끼리 연산함
# 브로드캐스팅; 잡아당기는 연산
# 잡아당기는 연산은 명시적인 메모리 복사가 일어나지 않음 • 속도/메모리 이득 • 브로드캐스 팅은 좋은 아이디어다 – 가능하면 사용하자
# I 브로드캐스팅과 꼴 (shape) 변환을 활용하면 루프를 피할 수 있음 • 뒤의 최단거리 이웃 예제 참조 • 고차원에서 생각하라
# 나하고 똑같은 것이 그대로 하나 더 있으면 메모리 공간을 차지하지 않음. 즉 브로드캐스팅 연산이 성능도 좋고 손도 덜 움직여서 좋은 기법
# 브로드캐스팅 이용해서 알고리즘을 만듦.

In [ ]:
# 넘파이를 꼭 알아야 함
# 넘파이는 gpu 안됨. mutable이라는 점도 문제점이 있음.

In [57]:
# 연산자 기능이 shape 에 따라 달라짐 - 다형성 관점
# 곱하기와 골뱅이.
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

In [58]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [59]:
np.dot(A, B)  # self 있어야 함

array([[5, 4],
       [3, 4]])

In [61]:
x,y = np.ogrid[1:10:5j, 1:10]

In [62]:
x
# j 가 complex만 있는 것이 아니다!!
# 연산자 오버로딩을 한 것.

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [ ]:
# stride 개념

In [74]:
a = np.arange(24).reshape(6,4)

In [75]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [76]:
a.strides
# 우리에게 보이는 모양은, 실제 구조는 1열로 되어 있는데, 스트라이드에 정의된 것에 따라 보이게 된다.
# 그 큰 값에서 특정값을 빠르게 가져오는 것도 스트라이드.
# 32씩 메모리 번지에 더하면 한 열에 있는 것 쉽게 가져올 수 있음.
# 32는 로우 넘어갈때의 메모리 간격, 8은 열 넘어갈때 메모리 간격

(32, 8)

In [77]:
a.itemsize  # 다음 열 가져올 때 얼만큼 값이 필요한지

8

In [78]:
# 축(axis) 에 대해서 들어가자!!
# 행마다, 열마다의 값에 대한 연산들이 빠르게 가져올 수 있음(스트라이드와 결합하면)
# 스트라이드 기반으로 한 axis
# axis = 0 ; 행마다(아래로) 연산
# axis = 1 ; 열마다(오른쪽으로) 연산
# 행마다 열마다 혼동될 때!!
a.shape

(6, 4)

In [79]:
a.sum()
# a.sum(axis=None, dtype=None, out=None, keepdims=False, initial=0, where=True)

276

In [80]:
# axis=0 행마다 다 더하니까 4개 나옴
a.sum(axis=0)

array([60, 66, 72, 78])

In [81]:
# axis=1 열마다 다 더하니까 6개 나옴
a.sum(axis=1)

array([ 6, 22, 38, 54, 70, 86])

In [82]:
# 3차원부터는 행, 열 이외에 차원이 있으니 이해가 안됨.
a = np.arange(24).reshape(2,3,4)

In [88]:
a, len(a)

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 2)

In [84]:
a.shape

(2, 3, 4)

In [85]:
# axis=0
# 0번째 지우고 (3,4) 형태의 결과값이 나옴. 
a.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [86]:
# axis=1
# 1번째 지우고 (2,4) 형태의 결과값이 나옴
a.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [87]:
# axis=2
# 2번째 지우고 (2,3) 형태의 결과값
a.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [ ]:
# 넘파이는 axis 관점이 있음. 여기에는 4차원 다 가능함.
# axis 도 차원을 reduction 한 것이라 볼 수 있음 => []를 없애는 것과 같음

In [90]:
a, a.shape

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 (2, 3, 4))

In [ ]:
# axis 는 매우 중요한 테크닉
# stride 는 convolution 으로 만들 수 있음.
# stride_trick 으로 convolution을 아주 빠르게 구현
# 지금은 중요하게 다루지 않음. 나중에 영상 다룰 때 할 것.
# array programming. 이게 없으면 for 문 돌려야 함

In [ ]:
# for 없이 다음 메모리에서 뽑아라 뽑아라 하니까 for가 필요없음.
# 함수형 패러다임 1장에서 배운 iterator, map, filter, reduce 등과 비슷함.
# 프로그래밍에서 가장 실수 많이 하는 것이 for

In [91]:
def asb(a,b):
    return a+b

In [92]:
asb([1,2,3],[3,4,5])

[1, 2, 3, 3, 4, 5]

In [93]:
@np.vectorize
def asb(a,b):
    return a+b

In [94]:
asb([1,2,3],[3,4,5])
# AOP 관점임. 나는 더하는 알고리즘(asb)만 집중하고 나머지는 np.vectorize 해서 기능 추가.

array([4, 6, 8])

In [95]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [97]:
'__iter__' in dir(a)   # for 돌릴 수 있음

True

In [98]:
for i in a:
    print(i)
# 3차원인데 2차원으로 나옴. 3차원 관점에서 원소가 2개 있음. 만약 2차원을 for문 했으면 1차원으로 나왔을 것

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [99]:
# 위와 같은 것 중에 하나의 예외가 있었음(다른 인덱싱과 리덕션은 싹다 차원을 하나씩 줄임)
# fancy indexing.
# 이것 말고 다 차원을 줄임.
a = np.arange(24).reshape(4,6)

In [100]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [101]:
for i in a:
    print(i)   # 내부적으로 iterator로 바뀌어서 돌아가기 때문에, 제일 큰 차원 관점에서 하나씩 보여줌

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]


In [103]:
# 보이는 건 n차로 보이는데 내부적으로는 다 1차임.
a.flatten() # 차원을 납작하게 만드는 것. 1차로 바꿔줌.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [104]:
a.flat  # iter가 보임

In [105]:
'__next__' in dir(a.flat)

True

In [106]:
b = a.flat

In [113]:
next(b)  # 즉 flat은 원소별로 돌릴 수 있음.

6

In [114]:
# 파이썬은 실수를 많이 할 수 있는 언어. for를 많이 쓸면 쓸수록 실수가 증가
# 함수형 패러다임은 함수만 잘 만들면 되기 때문에 논리에만 집중하면 됨.
# flat 도 두가지가 있음. flatten 하고 똑같은 애가 ravel()
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
# flatten 은 copy
# ravel 은 view
# 보이는 것 같은데 내부적으로는 다름.

In [ ]:
# Copies 와 View

In [115]:
a = [1,2,3]

In [116]:
b = a  # 이게 mutable 일 때는 메모리를 공유함

In [117]:
b[0] = 100

In [118]:
a

[100, 2, 3]

In [ ]:
# copy 를 해버리면?  # 공유 안할 때 쓰는 게 copy

In [143]:
a = [1,2,3]

In [120]:
b = a.copy()  # copy 하면 새롭게 메모리 상에 값 만듦
# 이렇게 하면 퍼포먼스 문제가 있음. 그 만큼 메모리 공간을 많이 차지함. 카피할 때 들어가는 비용이 있음.
# 텐서플로에도 카피를 씀.

In [121]:
b[0] = 100

In [122]:
a  # a 는 안바뀜

[1, 2, 3]

In [ ]:
# copy 2

In [123]:
a = [1,2,3]

In [124]:
b = a[:] # 이것도 copy임

In [125]:
# 인덱싱과 슬라이싱할 때 얘가 카피인지 아닌지 체크해야 함. 팬시 인덱싱에서 카피일 때가 있음.
# 확인하려면,
b[0] = 100

In [126]:
a # 안 바뀜. 그렇다면 [:]은 카피임

[1, 2, 3]

In [ ]:
# deep copy

In [130]:
a = [[1,2,3],[4,5,6]]

In [131]:
a

[[1, 2, 3], [4, 5, 6]]

In [132]:
b = a.copy()

In [133]:
b[0][0] = 100

In [134]:
a  # copy 가 안됐음. 이 deep 한 부분까지는 기본적으로 copy가 안됨. sharrow copy
# 여러 구조가 있으면 딱 한 구조만 카피가 됨

[[100, 2, 3], [4, 5, 6]]

In [135]:
# 따라서 deep copy
import copy

In [141]:
a = [[1,2,3],[4,5,6]]

In [137]:
b = copy.deepcopy(a)  # 구조체 안에 안에 들어간 것을 '딥'한 구조라고 함

In [138]:
b[0][0]=100

In [139]:
a

[[1, 2, 3], [4, 5, 6]]

In [ ]:
# 넘파이의 copy
# 넘파이는 ndarray 니까, 넘파이에서는 copy = deepcopy가 기본.
# flatten 은 copy -> 새로운 데이터 구조(deep)
# ravel 은 view -> 메모리 공유가 되어버림(shallow)
# 넘파이에서는 ctrl+z 가 없음. 주피터에는 기준점 체크포인트가 있음.
# 그래서 중요한 상황 나올 때마다 카피를 해 놓음
# 실행결과가 아주 많이 나온 경우도 카피를 해 놓음

In [ ]:
# shallow copy 를 view 라고 함.
# ravel() 은 view 다!
# 카피는 딥 카피다!!
# 인덱싱과 슬라이싱 할 떄 중요하다. 

In [147]:
a

[1, 2, 3]

In [148]:
b = a.copy()

In [149]:
c = a[:]

In [150]:
id(b) == id(c)

False

In [151]:
id(a) == id(b)

False

In [152]:
d = a

In [153]:
id(a) == id(d)

True